name: NS Resources
shortName: NSR
description: Articles, resources, tools, information, and guides related to National Service in Singapore. For NSFs from NSFs
sitemap: https://national-service.now.sh/sitemap.xml

pages:
  - links
  - about
  - dates
  - ippt
  - mn

footerLinks:
  - title: Dates
    url: /dates
    external: false
  - title: IPPT
    url: /ippt
    external: false
  - title: Discord
    url: /discord
  - title: r/NSSG
    url: /reddit
  - title: r/SG
    url: https://www.reddit.com/r/Singapore
  - title: CMPB
    url: https://www.cmpb.gov.sg/web/portal/cmpb/home/
  - title: GitHub
    url: https://github.com/ninest/nsr

redirects:
  - from: [discord, d]
    to: https://discord.com/invite/jZzsPGS
  - from: [reddit, r]
    to: https://www.reddit.com/r/NationalServiceSG/
  - from: [bmt, bmt/cqb]
    to: /basic-military-training
  - from: [telegram-ord-bot]
    to: /telegram-bots
